#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
# 									     #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com		     #
#	   José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

DOMAIN=$1
MAC=$2
SOURCE=$3
MODEL=$4
ID=$6

iFACE=0
NIC=$(ip a | grep ${ID}-eth$iFACE)

while [ -n "$NIC" ]; do
	let iFACE=iFACE+1
	NIC=$(ip a | grep ${ID}-eth$iFACE)
done


VM_PID=$(sudo lxc-info -pHn one-$ID)

sudo ip link add name ${ID}-eth${iFACE} type veth peer name ${ID}-eth${iFACE}-c
sudo brctl addif br0 ${ID}-eth${iFACE}
sudo ip link set dev ${ID}-eth${iFACE}-c netns $VM_PID name eth${iFACE} address $MAC
sudo ip link set ${ID}-eth${iFACE} up
