#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
# 									     #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com		     #
#	   José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #


VM_ID=$3

VM_ID=$3

while read HDDs; do
        if [ ! $HDDs = "disk.0" ]; then
                PRE_LOOP=$(sudo losetup -j /var/lib/one/datastores/0/$VM_ID/$HDDs)
                if [ -n "$PRE_LOOP" ]; then
                        LOOP_DEV=$(echo $PRE_LOOP | cut -f1 -d":")
                        sudo lxc-attach -e -n one-$VM_ID -- umount -l $LOOP_DEV
                        sudo losetup -d $LOOP_DEV
                fi
        fi
done < <(ls -1 /var/lib/one/datastores/0/$VM_ID)

while read iface; do
sudo lxc-attach -n one-$VM_ID ip link delete $iface
done < <(ip a | grep ${VM_ID}-eth | awk '{ print $2 }' | cut -d '-' -f 2 | cut -d ':' -f 1)


sudo lxc-stop -n one-${VM_ID}
sudo rm -rf /var/lib/lxc/one-${VM_ID} 

