#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

MAC=$2
VM_ID=$3

iFACE_DEL=$(sudo lxc-attach -n one-$VM_ID -- ip a | grep -B 1 $MAC | cut -d ':' -f 2 | sed -n '1 p')
exec_and_log "sudo lxc-attach -n one-$VM_ID ip link delete $iFACE_DEL"

_line=$(grep -in "lxc.network.hwaddr = $MAC" /var/lib/lxc/one-$VM_ID/config | awk 'NR==1' | cut -d ':' -f 1)
start_line=$((${_line}-7))
end_line=$((${_line}+2))
sed "$start_line,$end_line d" /var/lib/lxc/one-$VM_ID/config > /var/lib/lxc/one-$VM_ID/config_tmp && mv /var/lib/lxc/one-$VM_ID/config_tmp /var/lib/lxc/one-$VM_ID/config
