#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh


#DOMAIN=$1
DISK_SOURCE=$2
#TARGET=$3
TARGET_INDEX=$4
VM_ID=$5

DISK_ID=`echo $DISK_SOURCE | cut -d  '.' -f 2`
DEV_SOURCE=`sudo lxc-attach -n one-$VM_ID -- mount | grep "/media/$DISK_ID" | awk '{ print $1 }'`
DS_TYPE=`echo $DEV_SOURCE | cut -d '/' -f 3`

exec_and_log "sudo lxc-attach -e -n one-$VM_ID -- umount $DEV_SOURCE" "*******TARGET IS BUSY. Can't umount :(*******"
sudo lxc-attach -e -n one-$VM_ID -- rmdir /media/$DISK_ID

case $DS_TYPE in
	loop*)	sudo losetup -d $DEV_SOURCE
		start_line=$(grep -in "#--------------------Mounting disk $DISK_ID on one-${VM_ID}--------------------#" /var/lib/lxc/one-$VM_ID/vnc | awk 'NR==1' | cut -d ':' -f 1)
		end_line=$(($start_line+7))
		sed "$start_line,$end_line d" /var/lib/lxc/one-$VM_ID/vnc > /var/lib/lxc/one-$VM_ID/vnc_tmp && mv /var/lib/lxc/one-$VM_ID/vnc_tmp /var/lib/lxc/one-$VM_ID/vnc;;
	rbd*)	sudo rbd unmap $DEV_SOURCE
		start_line=$(grep -in "#--------------------Mounting disk $DISK_ID on one-${VM_ID}--------------------#" /var/lib/lxc/one-$VM_ID/vnc | awk 'NR==1' | cut -d ':' -f 1)
		end_line=$(($start_line+8))
		sed "$start_line,$end_line d" /var/lib/lxc/one-$VM_ID/vnc > /var/lib/lxc/one-$VM_ID/vnc_tmp && mv /var/lib/lxc/one-$VM_ID/vnc_tmp /var/lib/lxc/one-$VM_ID/vnc;;
	vg-one*) start_line=$(grep -in "#--------------------Mounting disk $DSK_ID on one-${VM_ID}--------------------#" /var/lib/lxc/one-$VM_ID/vnc | awk 'NR==1' | cut -d ':' -f 1)
		end_line=$(($start_line+3))
		sed "$start_line,$end_line d" /var/lib/lxc/one-$VM_ID/vnc > /var/lib/lxc/one-$VM_ID/vnc_tmp && mv /var/lib/lxc/one-$VM_ID/vnc_tmp /var/lib/lxc/one-$VM_ID/vnc;;
esac
