#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
# 									     #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com		     #
#	   José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #


DOMAIN=$1
SOURCE=$2
TARGET=$3
TARGET_INDEXX=$4
DRV_ACTION=$5
VM_ID=$5

TARGET_INDEX=$(echo $SOURCE | cut -d '.' -f 2)

LVM_LV=$(sudo lvdisplay | grep lv-one-${VM_ID}-$TARGET_INDEX)

if [ -n "$LVM_LV" ]; then
	sudo lxc-attach -e -n one-$VM_ID -- umount -l /dev/vg-one-0/lv-one-${VM_ID}-$TARGET_INDEX
else
	PRE_LOOP=$(sudo losetup -j /var/lib/one/datastores/0/$VM_ID/disk.$TARGET_INDEX)
	LOOP_DEV=$(echo $PRE_LOOP | cut -f1 -d":")
	sudo lxc-attach -e -n one-$VM_ID -- umount -l $LOOP_DEV
	sudo losetup -d $LOOP_DEV
fi
