#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
# 									     #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com		     #
#	   José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

MAC=$2
VM_ID=$6

while read iFACE_MAC; do
        if [ $iFACE_MAC = $MAC ]; then
                iFACE_DEL=$(sudo lxc-attach -n one-$VM_ID ip a | grep -B 1 $MAC | cut -d ':' -f 2 | sed -n '1 p')
		exec_and_log "sudo lxc-attach -n one-$VM_ID ip link delete $iFACE_DEL"
	fi
done < <(ip a | grep link/ether | awk '{ print $2 }')
