#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#          Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

##############################################################################
#                       SUSPENDER CONTENEDOR VIRTUAL                         #
##############################################################################

VM_ID=$4

exec_and_log "sudo lxc-freeze -n one-$VM_ID"

