#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
# 									     #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com		     #
#	   José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/kvmrc
source $(dirname $0)/../../scripts_common.sh

##############################################################################
#                          APAGAR CONTENEDOR VIRTUAL                         #
##############################################################################

VM_ID=$3
while read HDDs; do
        if [ ! $HDDs = "disk.0" ]; then
#		echo lista=$lista >> /home/kernel/one/det
		PRE_LOOP=$(sudo losetup -j /var/lib/one/datastores/0/$VM_ID/$HDDs)
#		echo pre_loop=$pre_loop >> /home/kernel/one/det
		if [ -n "$PRE_LOOP" ]; then
#		DISK_ID=$(echo $pre_loop | cut -f2 -d".")
#		echo DISK_ID2=$DISK_ID >> /home/kernel/one/det
#		lvm=$(sudo lvdisplay | grep lv-one-${VM_ID}-$DISK_ID)
#		if [ -n "$lvm" ]; then
#			echo DISK_IDinlvm=$DISK_ID >> /home/kernel/one/det
#			echo /dev/vg-one-0/lv-one-${VM_ID}-$DISK_ID >> /home/kernel/one/det
#			sudo lxc-attach -e -n one-$VM_ID -- umount -l /dev/vg-one-0/lv-one-${VM_ID}-$DISK_ID
#		else
			LOOP_DEV=$(echo $PRE_LOOP | cut -f1 -d":")
			sudo lxc-attach -e -n one-$VM_ID -- umount -l $LOOP_DEV
			sudo losetup -d $LOOP_DEV
        	fi
	fi
done < <(ls -1 /var/lib/one/datastores/0/$VM_ID)


while read iFACE; do
sudo lxc-attach -n one-$VM_ID -- ip link delete $iFACE
done < <(ip a | grep ${VM_ID}-eth | awk '{ print $2 }' | cut -d '-' -f 2 | cut -d ':' -f 1)


exec_and_log "sudo lxc-stop -n one-$VM_ID"
exec_and_log "sudo rm -rf /var/lib/lxc/one-${VM_ID}" "Can't delete container's folder (/var/lib/lxc/one-${VM_ID})"
