#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2016, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

NAME="$2"
VM_ID="$3"
DOMAIN="one-$VM_ID"

sudo rsync -zqrtLap /var/lib/lxc/${DOMAIN}/snaps/${SNAP_ID}/ --exclude=disks /var/lib/lxc/${DOMAIN}/

while read DISK; do
	SRCE="/var/lib/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks/$DISK"
	TRGT=`sudo realpath var/lib/one/datastores/0/${VM_ID}/$DISK`
	sudo rsync -zqrtLap $SRCE $TRGT
done < <(ls -1 /var/lib/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks)

sudo lxc-stop -n $DOMAIN

sudo lxc-wait -n $DOMAIN -s STOPPED

sudo lxc-start -n $DOMAIN

exit 0
