#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2016, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

SNAP_ID="$2"
VM_ID="$3"
#HOST="$4"
DOMAIN="one-${VM_ID}"

sudo mkdir -p /var/lib/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks

sudo lxc-freeze -n $DOMAIN

sudo rsync -zqrtaLp /var/lib/lxc/${DOMAIN}/ --exclude=snaps --exclude=rootfs.dev /var/lib/lxc/${DOMAIN}/snaps/${SNAP_ID}

sudo rsync -zqrtLap /var/lib/one/datastores/0/${VM_ID}/ --exclude=*.iso /var/lib/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks

if [ "$?" = "0" ]; then
    echo "${SNAP_ID}"
else
    sudo lxc-unfreeze -n $DOMAIN
    error_message "Could not create snapshot $NAME for domain $DOMAIN."
    exit -1
fi

sudo lxc-unfreeze -n $DOMAIN

exit 0
